version: '3.10'
services:
  preprocess:
    build:
      context: ./components/preprocess
      dockerfile: Dockerfile
    image: asia-northeast1-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPOSITORY_NAME}/preprocess:latest
  train:
    build:
      context: ./components/train
      dockerfile: Dockerfile
    image: asia-northeast1-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPOSITORY_NAME}/train:latest
  evaluate:
    build:
      context: ./components/evaluate
      dockerfile: Dockerfile
    image: asia-northeast1-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPOSITORY_NAME}/evaluate:latest
  deploy:
    build:
      context: ./components/deploy
      dockerfile: Dockerfile
    image: asia-northeast1-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPOSITORY_NAME}/deploy:latest
  serving:
    build:
      context: ./serving
      dockerfile: Dockerfile
    image: asia-northeast1-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPOSITORY_NAME}/serving:latest
    stdin_open: true
